### ISSUE TITLE
Package template as a gem

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#126]
> One of the challenges in making use of the tech docs template long term and for considering the addition of new features to tech docs is that the tool is packaged as a starting point for your microsite that you diverge from rather than a dependency that you manage. It would be easier to evolve with tech-docs-template if it was packaged in the form of a gem, rather than a middleman template.
> Feedback from @kevindew

**Comment by pgchamberlin** [comment]
@soupdragon99 I can't infer much from this. Is it something @tijmenb might know about?

**Comment by soupdragon99** [comment]
This is a suggestion from @kevindew

**Comment by tijmenb** [comment]
@36degrees do you have more context on the options around the distribution of the tech-docs-template? Are there examples of middleman templates that are distributed differently?

I remember you and Josh / Henry discussing this, but I don't know if there are feasible alternatives to the current method.

**Comment by 36degrees** [comment]
I am not aware of any way to distribute a middleman template as a gem. This is the recommended way to create sites from a template, as per [Middleman's docs](https://middlemanapp.com/advanced/project-templates/).

On top of that, we have done a lot of work to make it easy for individual documentation projects to stay up to date with the latest version of the template, as per the documentation in the README. It's just that most teams aren't doing so, and I am not convinced that they are any more likely to update if it was a gem.

Worth noting that the GOV.UK developer docs are a bit of an outlier given the number of changes that have been made to the functionality, which might be making the update process that little bit more complicated.

**Comment by tijmenb** [comment]
Thanks @36degrees!

This issue was raised (via the spreadsheet) while working on https://github.com/alphagov/govuk-content-api-docs. @kevindew do you remember what prompted it specifically?

**Comment by kevindew** [comment]
Hello :wave:

This was prompted by a couple of things, and a caveat that I'm not hip to all things Middleman.

**Template vs Dependency**

As I tried to describe, probably badly, it does a seem a somewhat odd situation having various files all in the repos (and many repos) with caveats of "do not edit them". Files like this: https://github.com/alphagov/govuk-developer-docs/blob/master/lib/DONT_TOUCH.md seemed a bit alarm bells to me, and more an approach of how things are normally communicated via a dependency.

But I'd agree that if this is the way it's done with middleman then that's less surprising than rolling a new approach.

**Talking with tech writers about the project**

Then on the other side, and I appreciate I may be wandering into contentious waters here 🙈 , from chats with the tech writer team about what they intend to develop for the tech docs; features such as: OpenAPI documentation, API explorer, etc. It doesn't feel like those features belong in a template and that doing so would make this very bloated.

My little brain conjures up that'd it'd be nice to have a gemfile like

```
gem "govuk_tech_docs"
gem "govuk_tech_docs_api_explorer"
```

Whereas this all seems a bit muddier if you have the template approach where you want bare minimum contents.

But naturally, as this second point is looking towards the future it's not worth considering if the former point is untenable.

Hope this has explained somewhat.

**Comment by tijmenb** [comment]
Before the holidays I started prototyping a mixed gem/template approach.

The current way of working is this repo (https://github.com/alphagov/tech-docs-template) contains all the code. It's a middleman template generator, and when the user generates a new site (`middleman init my-new-project -T alphagov/tech-docs-template`), it will create/copy a lot of files.

Perhaps an improvement would be to extract most of the code from the template into a gem. The generator (this repo) can generate a very small site which does the bare minimum to pull in code and assets from a separately managed gem.

Here's a prototype: https://github.com/alphagov/govuk-tech-docs-as-a-gem contains all code, CSS, JS, images and HTML for a middleman site.

A generated site (generated by `middleman init my-new-project -T alphagov/tech-docs-template`) would look like this:

https://github.com/alphagov/govuk-tech-docs-as-a-gem-poc-of-generated-site

The only thing we need in a generated site is:

- A [Gemfile to pull in the library](https://github.com/alphagov/govuk-tech-docs-as-a-gem-poc-of-generated-site/blob/master/Gemfile)
- A [small config.rb](https://github.com/alphagov/govuk-tech-docs-as-a-gem-poc-of-generated-site/blob/master/config.rb) to configure middleman
- The [YAML config file](https://github.com/alphagov/govuk-tech-docs-as-a-gem-poc-of-generated-site/blob/master/config/tech-docs.yml)
- One [javascript file to pull in the JS from the gem](https://github.com/alphagov/govuk-tech-docs-as-a-gem-poc-of-generated-site/blob/master/source/javascripts/application.js)
- One [CSS file to pull in the styles from the gem](https://github.com/alphagov/govuk-tech-docs-as-a-gem-poc-of-generated-site/blob/master/source/stylesheets/screen.css.scss)

The upsides of this:

- Updating to the latest version is easier, since in most versions you can just bump the gem version (Dependabot or similar services can even do this for us).
- Generated sites contain mostly custom code, making it easier to understand for developers which things are owned by the template and which things are for the instance.
- It's not possible to edit files that belong to the template, which would make upgrading very hard.
- Development is easier because developer can test a new version of the gem against their own project first, and then contributing back.

Downsides:

- The initial upgrade to this approach will be slightly annoying because projects that use the template will have to delete a lot of files and update the Gemfile.
- We have to release the gem to Rubygems

Thoughts? 

cc @alphagov/tech-docs @alphagov/team-reliability-engineering-tools-devs @tomnatt

**Comment by richardTowers** [comment]
Big 👍 from me - feels super gross to have to commit all the template files, and then risk someone editing them directly and not being able to upgrade.

Perhaps we could ship a script to ease the pain of deleting all the old template files as part of the upgrade to ease the first bit of pain.
