### ISSUE TITLE
Links - Anchor links

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#135]
1 page issue - there are a number of items listed on this sheet that could be resolved if we moved away from a one-page format and introduced search functionality (I mention this because my understanding is that we decided to use the one page format partly in response to not having a 'proper' way to search through content). I think this issue might also be resolved that way as there would be less of a need to use anchors if content didn't only live on one long page.

**Comment by pgchamberlin** [comment]
@soupdragon99 this definitely needs more information. What's the problem with anchors?

**Comment by J-Lambo** [comment]
Previous comment from @jonathanglassman:

Anchor links regularly get broken as sections are renamed based on research: There’s no way to redirect from one anchor to another.
A broken anchor will leave you at the top of the very long page, rather than a specific section where you may be able to find your way back.
We don’t think we get any 404 or analytics information on whether there are external links we need to get fixed (e.g. prototyping kit)

**Comment by pgchamberlin** [comment]
Ah, that's clear now. Thanks Jen.

**Comment by tijmenb** [comment]
This isn't something that can ever be fixed in the current setup, it's a side effect of the single page mechanism. Shall we merge this into https://github.com/alphagov/tech-docs-template/issues/128?

**Comment by tijmenb** [comment]
This is being considered for an outsourced project by GaaP to improve the usability of the template. Stay tuned.

**Comment by nickcolley** [comment]
It seems like we've had a bunch of good improvements to allow for multipage and search.

So with this in mind I'm going to close this one out, however if it's still relevant to you please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).
