### ISSUE TITLE
Maintain the scroll position of the sidebar navigation across new pages

### ISSUE THREAD

**Issue by lewisnyman** [alphagov/tech-docs-template#155]
One feedback I received when testing the new multi page navigation was that the scroll position of the sidebar navigation jumps around when you're clicking into different pages. This can disorient people who are browsing content on several pages, as they have to adjust the scroll position to understand their location in the IA.

Something like [turbolinks/turbolinks](https://github.com/turbolinks/turbolinks) would work, and it would probably speed up page load time. We could also store the scroll position in the browser.

**Comment by 36degrees** [comment]
I would be wary of adopting something like turbolinks without doing in-depth accessibility testing – a lot of assistive technology will fail to work properly if you effectively disable the native page navigation event – it will no longer inform e.g. a non-sighted user that they have navigated to a new page when they click a link.

This can be mitigated but it takes a lot of work to re-implement something that you would otherwise normally get for free. The complete absence of any mention of accessibility on the turbolinks readme and within their issues makes me think it is unlikely this is the case.

**Comment by nickcolley** [comment]
I agree with Ollie on this one.

I'm doing some tidying up of older issues, if this is something that is still relevant to you please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).
